apiVersion: v1
data:
  index.html: |
    <hr />
    <table style="margin-left: auto; margin-right: auto;">
    <tbody>
    <tr>
    <td style="text-align: center;">LABLOCAL - TESTE</td>
    </tr>
    <tr>
    <td>
    <h1><span style="color: #3366ff;"><strong>Teste do K8S Lab</strong></span></h1>
    </td>
    </tr>
    <tr>
    <td style="text-align: center;">&nbsp;Ingress - OK</td>
    </tr>
    </tbody>
    </table>
    <hr />
    <p>&nbsp;</p>
kind: ConfigMap
metadata:
  name: welcome
  labels:
    app: webserver
