apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: goapp
spec:
  rules:
  - host: goapp.my-ip-addr.sslip.io
    http:
      paths:
      - backend:
          service:
            name: goapp
            port:
              number: 8080
        path: /api
        pathType: Prefix
      - backend:
          service:
            name: landing-page
            port:
              number: 8080
        path: /
        pathType: Exact