apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: goapp
spec:
  rules:
  - host: goapp.23.23.80.169.sslip.io
    http:
      paths:
      - backend:
          service:
            name: landing-page
            port:
              number: 8080
        path: /
        pathType: Exact
